// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Usmp.Fia.NetCoreWebAplication.AppBitacoras.Data;

namespace Usmp.Fia.NetCoreWebAplication.AppBitacoras.Migrations
{
    [DbContext(typeof(BitacorasContexto))]
    partial class BitacorasContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.ActividadesPorGrupo", b =>
                {
                    b.Property<int>("idactividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("actividades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modif")
                        .HasColumnType("datetime2");

                    b.Property<int>("idgrupo")
                        .HasColumnType("int");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idactividad");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.Bitacora", b =>
                {
                    b.Property<int>("idbitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_entrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modif")
                        .HasColumnType("datetime2");

                    b.Property<int>("idasesor")
                        .HasColumnType("int");

                    b.Property<int>("idgrupo")
                        .HasColumnType("int");

                    b.Property<int>("idsemestre")
                        .HasColumnType("int");

                    b.Property<string>("observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idbitacora");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.Docentes", b =>
                {
                    b.Property<int>("iddocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modif")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombrecompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iddocente");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.Estudiantes", b =>
                {
                    b.Property<int>("idestudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modif")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombrecompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idestudiante");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.Grupo", b =>
                {
                    b.Property<int>("idgrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idasesor")
                        .HasColumnType("int");

                    b.Property<string>("observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idgrupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.IntegrantesPorGrupo", b =>
                {
                    b.Property<int>("IdIntegrantesPorGrupos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idestudiante")
                        .HasColumnType("int");

                    b.Property<int>("idgrupo")
                        .HasColumnType("int");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIntegrantesPorGrupos");

                    b.ToTable("IntegrantesPorGrupos");
                });

            modelBuilder.Entity("Usmp.Fia.NetCoreWebAplication.AppBitacoras.Entidades.Semestres", b =>
                {
                    b.Property<int>("idsemestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modif")
                        .HasColumnType("datetime2");

                    b.Property<string>("semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_crea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_modif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idsemestre");

                    b.ToTable("Semestres");
                });
#pragma warning restore 612, 618
        }
    }
}
